# Nixpacks configuration for backend-only deployment
# This overrides any auto-detection of Next.js

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["npm ci --production=false || npm install --production=false"]

[phases.build]
cmds = ["bash scripts/build-backend-railway.sh"]

[start]
cmd = "node dist/lib/server.js"

[variables]
NODE_ENV = "production"
PORT = "${PORT:-3001}"