# Nixpacks configuration for backend-only deployment
# This overrides any auto-detection of Next.js

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

# Skip install phase - our build script handles everything
[phases.install]
cmds = ["echo 'Skipping install phase - handled by build script'"]

[phases.build]
cmds = ["bash scripts/build-backend-railway.sh"]

[start]
cmd = "node dist/lib/server.js"

[variables]
NODE_ENV = "production"
PORT = "${PORT:-3001}"